export const JOBS_API_URI = 'https://joblify2.herokuapp.com/api/jobs'
export const LOCATION_API_URI = 'https://joblify2.herokuapp.com/api/locations'
export const API_URI = 'https://joblify2.herokuapp.com/api/'

export const JOBS_LOADING = 'JOBS_LOADING'
export const JOBS_SUCCESS = 'JOBS_SUCCESS'
export const JOBS_ERROR = 'JOBS_ERROR'

export const JOB_LOADING = 'JOB_LOADING'
export const JOB_SUCCESS = 'JOB_SUCCESS'
export const JOB_ERROR = 'JOB_ERROR'

export const LOCATION_LOADING = 'LOCATION_LOADING'
export const LOCATION_SUCCESS = 'LOCATION_SUCCESS'
export const LOCATION_ERROR = 'LOCATION_ERROR'

export const GOOGLE_AUTH_LOADING = 'GOOGLE_AUTH_LOADING'
export const GOOGLE_AUTH_SUCCESS = 'GOOGLE_AUTH_SUCCESS'
export const GOOGLE_AUTH_ERROR = 'GOOGLE_AUTH_ERROR'

export const GOOGLE_LOGOUT_LOADING = 'GOOGLE_LOGOUT_LOADING'
export const GOOGLE_LOGOUT_SUCCESS = 'GOOGLE_LOGOUT_SUCCESS'
export const GOOGLE_LOGOUT_ERROR = 'GOOGLE_LOGOUT_ERROR'

export const USER_SIGNUP_LOADING = 'USER_SIGNUP_LOADING'
export const USER_SIGNUP_SUCCESS = 'USER_SIGNUP_SUCCESS'
export const USER_SIGNUP_ERROR = 'USER_SIGNUP_ERROR'

export const USER_SIGNIN_LOADING = 'USER_SIGNIN_LOADING'
export const USER_SIGNIN_SUCCESS = 'USER_SIGNIN_SUCCESS'
export const USER_SIGNIN_ERROR = 'USER_SIGNIN_ERROR'

export const VISITOR_CREATE_LOADING = 'VISITOR_CREATE_LOADING'
export const VISITOR_CREATE_SUCCESS = 'VISITOR_CREATE_SUCCESS'
export const VISITOR_CREATE_ERROR = 'VISITOR_CREATE_ERROR'

export const VISITOR_GET_LOADING = 'VISITOR_GET_LOADING'
export const VISITOR_GET_SUCCESS = 'VISITOR_GET_SUCCESS'
export const VISITOR_GET_ERROR = 'VISITOR_GET_ERROR'

export const VISITOR_ADD_FAVORITE_LOADING = 'VISITOR_ADD_FAVORITE_LOADING'
export const VISITOR_ADD_FAVORITE_SUCCESS = 'VISITOR_ADD_FAVORITE_SUCCESS'
export const VISITOR_ADD_FAVORITE_ERROR = 'VISITOR_ADD_FAVORITE_ERROR'

export const VISITOR_REMOVE_FAVORITE_LOADING = 'VISITOR_REMOVE_FAVORITE_LOADING'
export const VISITOR_REMOVE_FAVORITE_SUCCESS = 'VISITOR_REMOVE_FAVORITE_SUCCESS'
export const VISITOR_REMOVE_FAVORITE_ERROR = 'VISITOR_REMOVE_FAVORITE_ERROR'

export const VISITOR_ADD_SKILL_LOADING = 'VISITOR_ADD_SKILL_LOADING'
export const VISITOR_ADD_SKILL_SUCCESS = 'VISITOR_ADD_SKILL_SUCCESS'
export const VISITOR_ADD_SKILL_ERROR = 'VISITOR_ADD_SKILL_ERROR'

export const VISITOR_REMOVE_SKILL_LOADING = 'VISITOR_REMOVE_SKILL_LOADING'
export const VISITOR_REMOVE_SKILL_SUCCESS = 'VISITOR_REMOVE_SKILL_SUCCESS'
export const VISITOR_REMOVE_SKILL_ERROR = 'VISITOR_ADD_SKILL_ERROR'

export const ADD_SKILL_LOADING = 'ADD_SKILL_LOADING'
export const ADD_SKILL_SUCCESS = 'ADD_SKILL_SUCCESS'
export const ADD_SKILL_ERROR = 'ADD_SKILL_ERROR'

export const GET_SKILLS_LOADING = 'GET_SKILLS_LOADING'
export const GET_SKILLS_SUCCESS = 'GET_SKILLS_SUCCESS'
export const GET_SKILLS_ERROR = 'GET_SKILLS_ERROR'
